spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/logins?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=bca123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
