spring.application.name=task
spring.datasource.url=jdbc:mysql://localhost:3306/taskdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Adi@758493

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true